spring.application.name=ex-ch03

#log level
logging.level.root=info
logging.level.com.example.demo = debug

#server port setting
server.port=8090

#encoding setting 하하
server.servlet.encoding.charset=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.http.encoding.enabled=true

#log file create
#logging.file.name=log/app.log